### ISSUE TITLE
Configuration got stuck while terminal still running.

### ISSUE THREAD

**Issue by brianchennn** [buihuukhoi/CREME#2]
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/46628572/115808133-7c840b00-a41c-11eb-8138-aaef8c59a3ab.png">

As the screenshot, I have no idea why Configuration step got stuck, but terminal still run and print some message normally.
I use bridge interface and have made sure that controller can use "root" to ssh login all machines.

The controller is in MacBook. 
Others are in Windows 10 Laptop.

**Comment by buihuukhoi** [comment]
I have fixed this in: c6a04d169fea6fe2dd3773494ad2f6f96cefa9ac
