### ISSUE TITLE
Data Processing got stuck 

### ISSUE THREAD

**Issue by okdercho** [buihuukhoi/CREME#4]
![Untitled](https://user-images.githubusercontent.com/83159858/115986740-45f8ec80-a5e4-11eb-9ccb-d2c13517261e.png)
![2](https://user-images.githubusercontent.com/83159858/115986739-44c7bf80-a5e4-11eb-9c0e-64bbde5da334.png)

As the screenshot, I have no idea why Data Processing step got stuck, but terminal still run and print some message normally.

In addition, I found that the VM capacity of Controller and Datalog continues to increase.

After running 9 hours
Datalog: 129 GB
Controller: 127 GB

**Comment by buihuukhoi** [comment]
This issue appeared in the old version of CREME.
Please try the new version of CREME.
Also, please download a new version of the attacker server (the same link) if you are using the old version.
