### ISSUE TITLE
Stuck at Phase 1

### ISSUE THREAD

**Issue by ChungHsuanChen** [buihuukhoi/CREME#5]
I have tried running CREME many times. 
However, over about 12  hours ,it always stuck at Phase1 as the picture below.
And the terminal still keeps running.
I use 8 VMs .Four Vms are created by myself,and the others are imported by provided.

![image](https://user-images.githubusercontent.com/73817114/117752091-c3f5fe00-b248-11eb-91aa-3b2f144cfaac.png)

**Comment by ChungHsuanChen** [comment]
Sorry,I closed it.
I will run it again immediately.
But I remembered the terminal that run tasks is blank and there is only the terminal cursor .

**Comment by ChungHsuanChen** [comment]
The terminal of running tasks :

![image](https://user-images.githubusercontent.com/73817114/117801152-8d3ed880-b286-11eb-8463-7cf2d28303f1.png)

redis server

![image](https://user-images.githubusercontent.com/73817114/117801287-b52e3c00-b286-11eb-8f4a-86cab87dc40a.png)

for HTTP

![image](https://user-images.githubusercontent.com/73817114/117801367-c8410c00-b286-11eb-973d-242d806cbdf1.png)

**Comment by buihuukhoi** [comment]
You are showing the terminal of running tasks with empty messages.
Could you please show the last messages on that terminal?

**Comment by ChungHsuanChen** [comment]
Before it got blank,It jumps y continuously.
The terminal of running tasks keeps running but I can't see the message.
Does the problem come from RAM?

**Comment by buihuukhoi** [comment]
How many GB of RAM are you using for the controller (how about trying with more than 4GB)?
BTW, could I know where the path of the CREME folder is? And which is the controller's path you filled on the website?

**Comment by ChungHsuanChen** [comment]
I use 8GB for the controller.
CREME folder path might be in /home
The controller path I filled in is /home/controller

**Comment by buihuukhoi** [comment]
If you stored the CREME folder path at "/home",
please fill in the controller path as "/home".
You should fill in this information correctly.

**Comment by ChungHsuanChen** [comment]
I fill it and ran it yesterday.
So far,it still stuck at Attack phase 1.
How long does it take roughly?
Thanks.

**Comment by buihuukhoi** [comment]
The attack phase 1 takes around ~10 mins to finish.
Could you please confirm where is the location of CREME?
(Go to /home and /home/controller, use the "ls" command to list all folders and files)
Then fill in the correct path into the website.

BTW, to ensure the system doesn't have any process that using APT, please wait for some minutes after you restart the machines, then run CREME

**Comment by ChungHsuanChen** [comment]
The folder is below.It,s in /home/controller
![folder2](https://user-images.githubusercontent.com/73817114/119251708-7f6c4a00-bbda-11eb-8cf3-5d63e9b7a5d7.PNG)

I filll the controller field as below
![controller2](https://user-images.githubusercontent.com/73817114/119251732-9e6adc00-bbda-11eb-9c52-a8122975db2a.PNG)

If there isn't any incorrect field, the problem might be the insufficient of my RAM.
Because there are only two 8GB RAM on my host.

**Comment by buihuukhoi** [comment]
It seems all information is correct.
Could you please wait 5~10 mins after reset all machines back to the previous snapshot version? Then you can run CREME. Its purpose is to make sure you don't have other processes that used APT.
I think the problem with memory only gets you stuck in the processing data step, not in the attack steps.

**Comment by ChungHsuanChen** [comment]
I usually wait 5-10 minutes before I run CREME.
I ran it again yrsterday.
And it goes ahead to the next phase, but it still stuck. 
![0527](https://user-images.githubusercontent.com/73817114/119345745-e6b5f700-bccb-11eb-80a9-4c9f0077c268.PNG)

**Comment by buihuukhoi** [comment]
Could I know which version of attacker_server you downloaded (is it after or before Mar 19)?
Also, could you please show the message on the terminal for this problem?

**Comment by ChungHsuanChen** [comment]
I downloaded it at 5th,May.
The terminal shows as same as above.
The only difference is it go ahead to attack phase 2.

**Comment by ChungHsuanChen** [comment]
Below are other machines .
![data-log](https://user-images.githubusercontent.com/73817114/119622111-7200cb00-be39-11eb-9d58-0dd191f041d9.JPG)
![non](https://user-images.githubusercontent.com/73817114/119622123-74632500-be39-11eb-9736-57177afb064c.JPG)
![benign](https://user-images.githubusercontent.com/73817114/119622135-76c57f00-be39-11eb-8f09-e2b200513e66.JPG)
![mali](https://user-images.githubusercontent.com/73817114/119622141-788f4280-be39-11eb-9ce2-7cad91f5c648.JPG)
I want to know whether there  is something I filled incorrect.
Thanks.

**Comment by buihuukhoi** [comment]
It seems all information is correct.
If you are sure that you followed the documents, could you please give me remote access to your testbed (you can give me this information through email)? I try to check which the problem is.

**Comment by ChungHsuanChen** [comment]
OK, I sent it.

**Comment by buihuukhoi** [comment]
Found a problem in telnet configuration.
Updated the document to fix the problem.
